#! /usr/bin/env php -q
<?php
/**
 * eGloo Framework Control Script
 *
 * This file contains the control script for the eGloo framework
 *
 * Copyright 2011 eGloo, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author George Cooper
 * @copyright 2011 eGloo, LLC
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * @package Scripts
 * @version 1.0
 */

// Check for the minimum PHP version to run the framework
if (version_compare(PHP_VERSION, '5.3.0', '<')) {
	echo 'You are using PHP version ' . PHP_VERSION . '.  ' .
		'eGloo requires PHP version 5.3.0 or higher.';
	exit;
} else {
	// Setup the OOP autoloader
	include( 'PHP/Includes/eGlooCLIAutoload.php' );
}

// Check for Memcache
if (!extension_loaded('memcache') && !extension_loaded('memcached')) {
	echo 'Memcache support not detected.  Please install Memcache or Memcached for PHP';
	exit;
}

echo 'lkj';
print_r($argv);
print_r($argc);