#! /usr/bin/env bash
#
# eGloo Framework Memcached Restart Script
#
# Script should be chmod 700 and run from the working directory
# using the command restartmemcache <args>
#
# Copyright 2010 eGloo, LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#  
# @author George Cooper
# @copyright 2011 eGloo, LLC
# @license http://www.apache.org/licenses/LICENSE-2.0
# @package Scripts
# @subpackage Runtime Tools
# @version 1.0

# Exit the script if any variables specified are unset when accessed
set -o nounset

# Exit the script if any statement returns a non-true value
# This prevents errors from cascading
set -o errexit

# Exit Error Codes
E_XCD=01       # Script can't change directories
E_NOTROOT=02   # Script not run as root

# Script Constants
ROOT_UID=0     # Only users with $UID 0 have root privileges.

# Check for root
if [[ "$UID" -ne "$ROOT_UID" ]]
then
	echo "***********************************"
	echo "* Must be root to run this script *"
	echo "***********************************"
	echo
	exit $E_NOTROOT
fi

killall memcached

instances=10

MEMCACHE_DAEMON=`locate */bin/memcached | head -n 1`

for ((n=1; n<=$instances; n++))
do
	((port=(11210+$n)))
	
	$MEMCACHE_DAEMON -u nobody -l 127.0.0.1 -m 24 -c 2048 -p $port -d
done
